name: .NET

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.2.2
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4.1.0
                with:
                    dotnet-version: 9.0.x
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Test
                run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' /p:ExcludeByAttribute="Tomlet.Attributes.NoCoverageAttribute"
            -   name: Build
                run: dotnet build -c Release
            -   name: Upload NuGet Artifact
                uses: actions/upload-artifact@v4.5.0
                with:
                    name: Tomlet.nupkg
                    path: Tomlet/bin/Release/*.nupkg
            -   name: Upload to NuGet
                if: github.event_name == 'push'
                env:
                    NUGET_API_KEY: ${{ secrets.GH_PAT }}
                run: dotnet nuget push ./Tomlet/bin/Release/*.nupkg -s https://nuget.pkg.github.com/RocketWerkz/index.json -k $NUGET_API_KEY